[project]
name = "firststreet"
version = "0.1.0"
description = "Add a short description here"
authors = ["Alexey Shiklomanov <alexey.shiklomanov@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.12.4,<3.13"
xarray = ">=2024.6.0,<2024.7"
h5netcdf = ">=1.3.0,<1.4"
geopandas = ">=0.14.4,<0.15"
rioxarray = ">=0.15.6,<0.16"
ipython = ">=8.25.0,<8.26"
